[package]
name = "smart_compass_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
defmt = "1.1.0"
defmt-rtt = "1.2.0"
embassy-boot-nrf = { version = "0.12.0", features = ["defmt"] }
embassy-executor = { version = "0.10.0", features = ["defmt", "platform-cortex-m", "executor-thread"] }
embassy-nrf = { version = "0.11.0", features = ["nrf52840", "time-driver-rtc1"] }
embassy-time = { version = "0.5.1", features = ["defmt"] }
embassy-sync = "0.8.0"
embassy-futures = "0.1.2"
embassy-embedded-hal = "0.6.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
static_cell = "2.1"
nrf-sdc = { version = "0.3.0", features = ["defmt", "peripheral", "nrf52840"] }
trouble-host = { version = "0.6.0", features = ["peripheral", "scan", "gatt"] }
panic-probe = { version = "0.3", features = ["print-defmt"] }

[build]
target = "thumbv7em-none-eabihf"
