[project]
name = "main"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "wildjames", email = "wild.james343@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
trace-widths = "main.trace_widths:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
